# Generated by Django 4.1.3 on 2022-12-01 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_products_img_alter_products_qtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='img_e',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
