# Generated by Django 4.1.3 on 2022-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_employees_img_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='img_e',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
