# Generated by Django 4.1.3 on 2022-12-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_employees_img_e_alter_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='bar_code',
        ),
        migrations.AddField(
            model_name='employees',
            name='id_e',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
