# Generated by Django 4.1.3 on 2022-12-05 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_employees_bar_code_employees_id_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.sails'),
        ),
    ]
