# Generated by Django 4.1.3 on 2022-12-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_inventory_sail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.sails'),
        ),
    ]
