# Generated by Django 4.1.3 on 2022-12-06 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_inventory_sail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mov',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='qtt',
            field=models.IntegerField(default=0),
        ),
    ]
